In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X=df.iloc[:,3:13]

In [5]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [6]:
y=df.iloc[:,13]

In [7]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
geography=pd.get_dummies(X['Geography'],drop_first=True)

In [9]:
geography

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [10]:
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [11]:
gender

Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [12]:
X=pd.concat([X,gender,geography],1)

In [13]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Male  Germany  Spain  
0             1               1        101348.88     0        0      0  
1             0               1        112542.58     0        0      1  
2             1               0        113931.57     0        0      0  
3             0               0         93826.63     0        0      0  
4             1               1         79084.10     0        0      1  
...         ...             ...              ...   ...      ...    ...  
9995          1               0         96270.64     1        0      0  
9996          1               1        101699.77     1        0      0  
9997          0               1         42085.58     0        0      0  
9998          1               0         92888.52     1        1      0  
9999          1               0         38190.78     0        0      0  

[10000 rows x 13 columns]

In [14]:
X=X.drop(['Geography','Gender'],1)

In [15]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Male  Germany  Spain  
0                  1        101348.88     0        0      0  
1                  1        112542.58     0        0      1  
2                  0        113931.57     0        0      0  
3                  0         93826.63     0        0      0  
4                  1         79084.10     0        0      1  
...              ...              ...   ...      ...    ...  
9995               0         96270.64     1        0      0  
9996               1        101699.77     1        0      0  
9997               1         42085.58     0        0      0  
9998               0         92888.52     1        1      0  
9999               0         38190.78     0        0      0  

[10000 rows x 11 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc=StandardScaler()

In [18]:
X=sc.fit_transform(X)

In [19]:
X

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=110)

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [23]:
classifier=Sequential()

In [24]:
classifier.add(Dense(units=10,kernel_initializer='he_uniform',activation='relu',input_dim=11))

In [25]:
classifier.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu'))

In [26]:
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [27]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [28]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7598 - val_loss: 0.4773 - val_accuracy: 0.7986
Epoch 2/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4548 - accuracy: 0.8046 - val_loss: 0.4397 - val_accuracy: 0.8092
Epoch 3/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4341 - accuracy: 0.8175 - val_loss: 0.4247 - val_accuracy: 0.8179
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4235 - accuracy: 0.8203 - val_loss: 0.4146 - val_accuracy: 0.8205
Epoch 5/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4149 - accuracy: 0.8248 - val_loss: 0.4046 - val_accuracy: 0.8213
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4069 - accuracy: 0.8274 - val_loss: 0.3980 - val_accuracy: 0.8251
Epoch 7/100
536/536 [==============================] - 1s 1ms/step - loss: 0.3992 - accuracy: 0.8341 - val_loss: 0.3898 - val_accuracy: 0.8315

In [30]:
model_history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [31]:
y_pred=classifier.predict(X_test)

In [32]:
y_pred

array([[0.05301529],
       [0.9776197 ],
       [0.17716646],
       ...,
       [0.09274381],
       [0.89244556],
       [0.06093729]], dtype=float32)

In [33]:
y_pred=(y_pred>0.5)

In [34]:
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [36]:
cm=confusion_matrix(y_test,y_pred)

In [37]:
cm

array([[1546,   43],
       [ 230,  181]], dtype=int64)

In [38]:
accuracy_score(y_test,y_pred)

0.8635

In [39]:
classifier.add(Dense(units=10,kernel_initializer='he_normal',activation='relu',input_dim=11))

In [40]:
classifier.add(Dense(units=20,kernel_initializer='he_normal',activation='relu',input_dim=11))

In [41]:
classifier.add(Dense(units=15,kernel_initializer='he_normal',activation='relu',input_dim=11))

In [42]:
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [43]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_4 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_5 (Dense)              (None, 15)                315       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 1

In [44]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 1s 3ms/step - loss: 0.5435 - accuracy: 0.7964 - val_loss: 0.5075 - val_accuracy: 0.7974
Epoch 2/100
536/536 [==============================] - 1s 1ms/step - loss: 0.5071 - accuracy: 0.7964 - val_loss: 0.5054 - val_accuracy: 0.7974
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7964 - val_loss: 0.5054 - val_accuracy: 0.7974
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.8000 - val_loss: 0.4367 - val_accuracy: 0.8289
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4328 - accuracy: 0.8281 - val_loss: 0.4246 - val_accuracy: 0.8353
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4242 - accuracy: 0.8334 - val_loss: 0.4198 - val_accuracy: 0.8353
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4201 - accuracy: 0.8373 - val_loss: 0.4196 - val_accuracy: 0.8342

In [46]:
y_pred=classifier.predict(X_test)

In [47]:
y_pred

array([[0.04111311],
       [0.97700185],
       [0.28759944],
       ...,
       [0.16015652],
       [0.9615792 ],
       [0.09881547]], dtype=float32)

In [48]:
y_pred=y_pred>0.5

In [49]:
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [50]:
accuracy_score(y_test,y_pred)

0.8605

In [51]:
confusion_matrix(y_test,y_pred)

array([[1537,   52],
       [ 227,  184]], dtype=int64)

In [52]:
classifier.add(Dense(units=10,kernel_initializer='he_normal',activation='relu',input_dim=11))
classifier.add(Dropout(0.3))
classifier.add(Dense(units=20,kernel_initializer='he_normal',activation='relu'))
classifier.add(Dropout(0.4))
classifier.add(Dense(units=15,kernel_initializer='he_normal',activation='relu'))
classifier.add(Dropout(0.2))
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [53]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7863 - val_loss: 0.4873 - val_accuracy: 0.7974
Epoch 2/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4224 - accuracy: 0.7962 - val_loss: 0.4132 - val_accuracy: 0.7974
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3924 - accuracy: 0.7962 - val_loss: 0.4393 - val_accuracy: 0.7974
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3862 - accuracy: 0.7964 - val_loss: 0.4095 - val_accuracy: 0.7974
Epoch 5/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3812 - accuracy: 0.8255 - val_loss: 0.4057 - val_accuracy: 0.8644
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3804 - accuracy: 0.8612 - val_loss: 0.4110 - val_accuracy: 0.8641
Epoch 7/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3846 - accuracy: 0.8580 - val_loss: 0.4285 - val_accuracy: 0.8614

In [54]:
y_pred=classifier.predict(X_test)

In [55]:
y_pred=y_pred>0.5

In [56]:
confusion_matrix(y_test,y_pred)

array([[1322,  267],
       [ 116,  295]], dtype=int64)

In [57]:
accuracy_score(y_test,y_pred)

0.8085