In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
geography=pd.get_dummies(df['Geography'],drop_first=True)
gender=pd.get_dummies(df['Gender'],drop_first=True)

In [5]:
df=pd.concat([df,gender,geography],1)

In [6]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Male  Germany  Spain  
0        101348.88       1     0        0      0  
1        112542.58       0     0        0      1  
2        113931.57       1     0        0      0  
3         93826.63       0     0        0      0  
4         79084.10       0     0        0      1

In [7]:
df.drop(['Gender','Geography'],1,inplace=True)

In [8]:
X=df.iloc[:,3:13]
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Male  
0                  1        101348.88       1     0  
1                  1        112542.58       0     0  
2                  0        113931.57       1     0  
3                  0         93826.63       0     0  
4                  1         79084.10       0     0  
...              ...              ...     ...   ...  
9995               0         96270.64       0     1  
9996               1        101699.77       0     1  
9997               1         42085.58       1     0  
9998               0         92888.52       1     1  
9999               0         38190.78       0     0  

[10000 rows x 10 columns]

In [9]:
y=df.iloc[:,-1]
y

0       0
1       1
2       0
3       0
4       1
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Spain, Length: 10000, dtype: uint8

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [13]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ...,  1.10643166,
        -0.50624244, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ..., -0.74866447,
        -0.50624244,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ...,  1.48533467,
        -0.50624244, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ...,  1.41231994,
        -0.50624244,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ...,  0.84432121,
        -0.50624244, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  0.32472465,
         1.97533814, -1.09168714]])

In [14]:
X_test

array([[-0.56129438, -0.39401698,  0.9869706 , ...,  1.62185911,
        -0.50390326, -1.11339196],
       [-1.33847768,  0.07611425, -1.08432132, ...,  0.504204  ,
         1.9845079 , -1.11339196],
       [ 0.58347561,  0.26416674,  0.9869706 , ..., -0.41865644,
        -0.50390326, -1.11339196],
       ...,
       [-0.76084144, -0.29999074, -1.42953664, ...,  0.72775202,
        -0.50390326,  0.8981563 ],
       [-0.0046631 , -0.48804323, -0.39389068, ..., -1.54162886,
        -0.50390326,  0.8981563 ],
       [-0.81335383, -0.86414821,  0.9869706 , ...,  1.62356528,
        -0.50390326,  0.8981563 ]])

In [15]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu,sigmoid

In [16]:
def create_model(layers,activation):
    model=Sequential()
    for i,nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))
    model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    model.summary()
    return model

In [17]:
model=KerasClassifier(build_fn=create_model,verbose=0)

In [18]:
layers=[(20), (40,20), (45,30,15)]

In [19]:
activations=['sigmoid','relu']

In [20]:
param_grid=dict(layers=layers,activation=activations,batch_size=[128,256],epochs=[30])

In [21]:
grid=GridSearchCV(estimator=model,param_grid=param_grid,cv=5)

In [30]:
param_grid

{'layers': [20, (40, 20), (45, 30, 15)],
 'activation': ['sigmoid', 'relu'],
 'batch_size': [128, 256],
 'epochs': [30]}

In [31]:
grid

GridSearchCV(cv=5,
             estimator=<tensorflow.python.keras.wrappers.scikit_learn.KerasClassifier object at 0x00000266D7571940>,
             param_grid={'activation': ['sigmoid', 'relu'],
                         'batch_size': [128, 256], 'epochs': [30],
                         'layers': [20, (40, 20), (45, 30, 15)]})

In [22]:
grid_result=grid.fit(X_train,y_train)

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 40)                440       
_________________________________________________________________
activation (Activation)      (None, 40)                0         
_________________________________________________________________
dropout (Dropout)            (None, 40)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 20)                820       
_________________________________________________________________
activation_1 (Activation)    (None, 20)                0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 20)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [35]:
[grid_result.best_score_,grid_result.best_params_]

[0.7523749947547913,
 {'activation': 'sigmoid',
  'batch_size': 128,
  'epochs': 30,
  'layers': (40, 20)}]

In [24]:
pred_y = grid.predict(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [25]:
y_pred = (pred_y > 0.5)

In [26]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [28]:
cm

array([[1504,    0],
       [ 496,    0]], dtype=int64)

In [29]:
accuracy_score(y_test,y_pred)

0.752

In [36]:
import tensorflow as tf
tf.test.gpu_device_name()

''

In [37]:
from tensorflow.python.client import device_lib 
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8448563605670327687,
 name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 6644578365141998140
 physical_device_desc: "device: XLA_CPU device",
 name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 588801548504973242
 physical_device_desc: "device: XLA_GPU device"]